"""Extract exercise thumbnails from the training-plan PDFs.

Each PDF has three sections (pull, push, combined) of numbered exercise rows.
Exercise images are YouTube thumbnails wrapped in a link; each one is assigned
to the row whose number marker sits directly above it.

Writes images to public/exercises/ and a typed mapping to
src/data/exerciseMedia.generated.ts keyed by seed exercise id.

Usage: python scripts/extract_exercise_images.py [--pdf-dir DIR]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "public" / "exercises"
TS_OUT = ROOT / "src" / "data" / "exerciseMedia.generated.ts"

PDFS: list[tuple[str, list[str]]] = [
    ("תכנית אימונים רועי חזם- בלוק 1.pdf", ["tpl-b1-pull", "tpl-b1-push", "tpl-b1-combo"]),
    ("תכנית אימונים רועי חזם- בלוק 2.pdf", ["tpl-b2-pull", "tpl-b2-push", "tpl-b2-combo"]),
]

ROW_NUMBER_MIN_X = 780
ROW_TOLERANCE = 5
MIN_THUMB_WIDTH = 50


@dataclass
class Row:
    section: int
    number: int
    y: float


def find_rows(page: pymupdf.Page, section_offset: int) -> list[Row]:
    rows: list[Row] = []
    section = section_offset - 1
    for block in page.get_text("dict")["blocks"]:
        for line in block.get("lines", []):
            for span in line["spans"]:
                text = span["text"].strip()
                if span["bbox"][0] < ROW_NUMBER_MIN_X or not re.fullmatch(r"\d", text):
                    continue
                number = int(text)
                if number == 1:
                    section += 1
                rows.append(Row(section, number, span["bbox"][1]))
    return sorted(rows, key=lambda r: r.y)


def save_image(doc: pymupdf.Document, xref: int, stem: str) -> str:
    info = doc.extract_image(xref)
    smask = info.get("smask") or 0
    if smask:
        pix = pymupdf.Pixmap(pymupdf.Pixmap(doc, xref), pymupdf.Pixmap(doc, smask))
        name = f"{stem}.png"
        pix.save(OUT_DIR / name)
    else:
        ext = "jpg" if info["ext"] in ("jpeg", "jpg") else info["ext"]
        name = f"{stem}.{ext}"
        (OUT_DIR / name).write_bytes(info["image"])
    return name


def extract(pdf_path: Path, template_ids: list[str]) -> dict[str, dict[str, str]]:
    doc = pymupdf.open(pdf_path)
    media: dict[str, dict[str, str]] = {}
    sections_seen = 0

    for page in doc:
        links = [l for l in page.get_links() if "youtube.com" in (l.get("uri") or "")]
        if not links:
            continue
        rows = find_rows(page, sections_seen)
        if not rows:
            continue
        sections_seen = rows[-1].section + 1

        for img in page.get_image_info(xrefs=True):
            bbox = pymupdf.Rect(img["bbox"])
            if bbox.width < MIN_THUMB_WIDTH:
                continue
            link = next((l for l in links if l["from"].intersects(bbox)), None)
            if link is None:
                continue
            row = max(
                (r for r in rows if r.y <= bbox.y0 + ROW_TOLERANCE),
                key=lambda r: r.y,
                default=None,
            )
            if row is None or row.section >= len(template_ids):
                print(f"  ! unmatched image xref={img['xref']} y={bbox.y0:.0f}", file=sys.stderr)
                continue
            exercise_id = f"{template_ids[row.section]}-{row.number}"
            file_name = save_image(doc, img["xref"], exercise_id)
            media[exercise_id] = {
                "imageUrl": f"/exercises/{file_name}",
                "videoUrl": link["uri"],
            }
            print(f"  {exercise_id:<16} <- xref {img['xref']:<4} {link['uri']}")

    if sections_seen != len(template_ids):
        print(f"  ! expected {len(template_ids)} sections, found {sections_seen}", file=sys.stderr)
    return media


def write_ts(media: dict[str, dict[str, str]]) -> None:
    body = json.dumps(dict(sorted(media.items())), ensure_ascii=False, indent=2)
    TS_OUT.write_text(
        "// Generated by scripts/extract_exercise_images.py. Do not edit by hand.\n"
        "export type ExerciseMedia = { imageUrl: string; videoUrl: string }\n\n"
        f"export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {body}\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pdf-dir", type=Path, default=ROOT)
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_DIR.glob("tpl-*"):
        old.unlink()

    media: dict[str, dict[str, str]] = {}
    for file_name, template_ids in PDFS:
        path = args.pdf_dir / file_name
        if not path.exists():
            sys.exit(f"PDF not found: {path}")
        print(f"== {file_name}")
        media.update(extract(path, template_ids))

    write_ts(media)
    print(f"Saved {len(media)} images to {OUT_DIR.relative_to(ROOT)}, mapping -> {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
