ALTER TABLE IF EXISTS workout_logs
  ADD COLUMN IF NOT EXISTS performed_on DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS estimated_calories INTEGER DEFAULT 0;

ALTER TABLE IF EXISTS client_app_state
  ADD COLUMN IF NOT EXISTS focus_tracks JSONB DEFAULT '[]'::jsonb;
