// Generated by scripts/extract_exercise_images.py. Do not edit by hand.
export type ExerciseMedia = { imageUrl: string; videoUrl: string }

export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {
  "tpl-b1-combo-2": {
    "imageUrl": "/exercises/tpl-b1-combo-2.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=kdplcxXH49I"
  },
  "tpl-b1-combo-3": {
    "imageUrl": "/exercises/tpl-b1-combo-3.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=LyZH4UGdDTc"
  },
  "tpl-b1-combo-5": {
    "imageUrl": "/exercises/tpl-b1-combo-5.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=xiSBrm-Rgms"
  },
  "tpl-b1-combo-6": {
    "imageUrl": "/exercises/tpl-b1-combo-6.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=xguGXQAvbKk"
  },
  "tpl-b1-pull-1": {
    "imageUrl": "/exercises/tpl-b1-pull-1.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=po3K41G0C-w"
  },
  "tpl-b1-pull-2": {
    "imageUrl": "/exercises/tpl-b1-pull-2.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=vsgxE97wBY0"
  },
  "tpl-b1-pull-3": {
    "imageUrl": "/exercises/tpl-b1-pull-3.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=kdplcxXH49I"
  },
  "tpl-b1-pull-4": {
    "imageUrl": "/exercises/tpl-b1-pull-4.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=LyZH4UGdDTc"
  },
  "tpl-b1-pull-5": {
    "imageUrl": "/exercises/tpl-b1-pull-5.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=fXFN8_1Bh6k"
  },
  "tpl-b1-push-2": {
    "imageUrl": "/exercises/tpl-b1-push-2.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=AUJtWOQRHPI"
  },
  "tpl-b1-push-3": {
    "imageUrl": "/exercises/tpl-b1-push-3.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=xiSBrm-Rgms"
  },
  "tpl-b1-push-4": {
    "imageUrl": "/exercises/tpl-b1-push-4.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=k6tzKisR3NY"
  },
  "tpl-b1-push-5": {
    "imageUrl": "/exercises/tpl-b1-push-5.jpg",
    "videoUrl": "https://www.youtube.com/watch?v=4qK55avGyy4"
  },
  "tpl-b2-combo-2": {
    "imageUrl": "/exercises/tpl-b2-combo-2.png",
    "videoUrl": "https://www.youtube.com/watch?v=iNXUkl_ccfc"
  },
  "tpl-b2-combo-4": {
    "imageUrl": "/exercises/tpl-b2-combo-4.png",
    "videoUrl": "https://www.youtube.com/watch?v=OskpsD1eDWw"
  },
  "tpl-b2-combo-5": {
    "imageUrl": "/exercises/tpl-b2-combo-5.png",
    "videoUrl": "https://www.youtube.com/watch?v=vSMH88caHow"
  },
  "tpl-b2-pull-2": {
    "imageUrl": "/exercises/tpl-b2-pull-2.png",
    "videoUrl": "https://www.youtube.com/watch?v=etkKNsYZozs"
  },
  "tpl-b2-pull-3": {
    "imageUrl": "/exercises/tpl-b2-pull-3.png",
    "videoUrl": "https://www.youtube.com/watch?v=iNXUkl_ccfc"
  },
  "tpl-b2-pull-4": {
    "imageUrl": "/exercises/tpl-b2-pull-4.png",
    "videoUrl": "https://www.youtube.com/watch?v=gLYfEoHA_Ac"
  },
  "tpl-b2-pull-5": {
    "imageUrl": "/exercises/tpl-b2-pull-5.png",
    "videoUrl": "https://www.youtube.com/watch?v=fXFN8_1Bh6k"
  },
  "tpl-b2-push-3": {
    "imageUrl": "/exercises/tpl-b2-push-3.png",
    "videoUrl": "https://www.youtube.com/watch?v=AGTlLisjNak"
  },
  "tpl-b2-push-6": {
    "imageUrl": "/exercises/tpl-b2-push-6.png",
    "videoUrl": "https://www.youtube.com/watch?v=13_idHEyvJ8"
  }
}
